# Generated by Django 2.1 on 2018-08-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='https://hackthatcore.blogspot.com', max_length=1500)),
                ('name', models.CharField(default='HackThatCORE Home', max_length=200)),
            ],
        ),
    ]
